/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.telcel.lectura;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author xoq5f10
 */
public class GUITiempos extends javax.swing.JFrame {
    Connection reg;

    
    /**
     * Creates new form GUITiempos
     */
    public GUITiempos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("reloj.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new Table();//javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiempos STT");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "TPE", "TPA", "Clientes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Centro:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] fecha;
        String centro=null;
        String texto;
        int pos=0;
        Connect con = new Connect();
        int btelcel=0,blg=0,bmotorola=0,bnokia=0,bsamsung=0,bsony=0,balcatel=0,bapple=0,bgeneral=0;
        String[] telcel = {"Telcel","00:00:00","00:00:00","0"};
        String[] lg = {"LG","00:00:00","00:00:00","0"};
        String[] motorola = {"Motorola","00:00:00","00:00:00","0"};
        String[] nokia = {"Nokia","00:00:00","00:00:00","0"};
        String[] samsung = {"Samsung","00:00:00","00:00:00","0"};
        String[] sony = {"Sony","00:00:00","00:00:00","0"};
        String[] alcatel = {"Alcatel","00:00:00","00:00:00","0"};
        String[] apple = {"Apple","00:00:00","00:00:00","0"};
        String[] general = {"General","00:00:00","00:00:00","0"};
        int c =0;
        
        fecha = this.jLabel4.getText().split("/");
        texto = this.jLabel2.getText();
        pos=texto.indexOf(" ");
        if(pos!=0){
           centro = texto.substring(pos).trim(); 
        }
        
        if(centro.equals("ETRAM El Rosario")){
            centro = "ETRAM Rosario";
         }
        if(centro.equals("Buenavista")){
            centro = "Forum Buenavista";
         }
        if(centro.equals("Galerías Pachuca")){
            centro = "Galerias Pachuca";
         }
        if(centro.equals("Interlomas")){
            centro = "Paseo Interlomas";
         }
        
        
        con.ConectarBasedeDatos();
        reg=con.getConnection();
        try{
        PreparedStatement pst=reg.prepareStatement("SELECT * FROM tpetpa1 WHERE STT = '"+centro+
                "' AND Dia ='"+fecha[0]+"' AND Mes ='"+fecha[1]+"' AND Ano = '"+fecha[2]+"'");
        con.resultado=pst.executeQuery();
        if(!con.resultado.next()){
            
            for(int i=0; i<this.jTable1.getRowCount(); i++){
                for(int j=0; j<this.jTable1.getColumnCount(); j++){
                    
                    if(jTable1.getValueAt(i, j).equals("Telcel")){
                        btelcel++;
                        c=0;
                    }if(btelcel!=0){
                        telcel[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){btelcel=0;}
                        c++;
                    }
                    
                    if(jTable1.getValueAt(i, j).equals("LG")){
                        blg++;
                        c=0;
                    }if(blg!=0){
                        lg[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){blg=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("Motorola")){
                        bmotorola++;
                        c=0;
                    }if(bmotorola!=0){
                        motorola[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){bmotorola=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("Nokia")){
                        bnokia++;
                        c=0;
                    }if(bnokia!=0){
                        nokia[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){bnokia=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("Samsung")){
                        bsamsung++;
                        c=0;
                    }if(bsamsung!=0){
                        samsung[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){bsamsung=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("Sony")){
                        bsony++;
                        c=0;
                    }if(bsony!=0){
                        sony[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){bsony=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("Alcatel")){
                        balcatel++;
                        c=0;
                    }if(balcatel!=0){
                        alcatel[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){balcatel=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("Apple")){
                        bapple++;
                        c=0;
                    }if(bapple!=0){
                        apple[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){bapple=0;}
                        c++;
                    }
                    if(jTable1.getValueAt(i, j).equals("General")){
                        bgeneral++;
                        c=0;
                    }if(bgeneral!=0){
                        general[j]=jTable1.getValueAt(i, j).toString();
                        if(c==3){bgeneral=0;}
                        c++;
                    }
                }
            }
            
            PreparedStatement pst2=reg.prepareStatement("INSERT INTO tpetpa1 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst2.setString(1, centro);pst2.setString(2,fecha[0]);pst2.setString(3, fecha[1]);pst2.setString(4, fecha[2]);
            pst2.setString(5, telcel[0]);pst2.setString(6, telcel[1]);pst2.setString(7, telcel[2]);pst2.setString(8, telcel[3]);
            pst2.setString(9, lg[0]);pst2.setString(10, lg[1]);pst2.setString(11, lg[2]);pst2.setString(12, lg[3]);
            pst2.setString(13, motorola[0]);pst2.setString(14, motorola[1]);pst2.setString(15, motorola[2]);pst2.setString(16, motorola[3]);
            pst2.setString(17, nokia[0]);pst2.setString(18, nokia[1]);pst2.setString(19, nokia[2]);pst2.setString(20, nokia[3]);
            pst2.setString(21, samsung[0]);pst2.setString(22, samsung[1]);pst2.setString(23, samsung[2]);pst2.setString(24, samsung[3]);
            pst2.setString(25, sony[0]);pst2.setString(26, sony[1]);pst2.setString(27, sony[2]);pst2.setString(28, sony[3]);
            pst2.setString(29, general[1]);pst2.setString(30, general[2]);pst2.setString(31, general[3]);
            pst2.setString(32, alcatel[0]);pst2.setString(33, alcatel[1]);pst2.setString(34, alcatel[2]);pst2.setString(35, alcatel[3]);
            pst2.setString(36, apple[0]);pst2.setString(37, apple[1]);pst2.setString(38, apple[2]);pst2.setString(39, apple[3]);
            pst2.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Registro actualizado","Notification",JOptionPane.INFORMATION_MESSAGE);
                         
             
         }else{JOptionPane.showMessageDialog(this,"El registro de la fecha "+this.jLabel4.getText()+" ya existe favor de validar","Exception",JOptionPane.ERROR_MESSAGE);}
        con.DesconectarBasedeDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Exception1",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITiempos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITiempos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITiempos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITiempos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITiempos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
